name: name
version: '3'
services:
  redis:
    container_name: redis
    build:
      context: ./
    restart: always
    ports:
      - "6379:6379"
    volume: 
      - toy_redis:/data
      # - /var/lib/docker/volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  toy_redis: