services:
  postgres:
    image: "postgres:latest"
    restart: always
    container_name: toy_postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123!
      POSTGRES_DB: postgres
    volumes:
      - toy-volume:/var/lib/postgresql/data
    ports:
      - 5431:5432

  # 서비스명
  redis_container:
    # 컨테이너명
    container_name: redis_test
    environment:
      - REDIS_MAXMEMORY=256mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    build:
      context: ./redis
    ports:
      - 6379:6379
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - redis:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always

volumes:
  toy-volume:
  redis:
